FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BX_Services.csproj", "./"]
RUN dotnet restore "BX_Services.csproj"
COPY . .
RUN dotnet publish "BX_Services.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BX_Services.dll", "--project", "BX_Services.csproj"]
